namespace MVerse.VARMAP.Enum
{
    public enum VARMAP_Variable_ID
    {
        /* > ATG 1 START < */
        VARMAP_ID_NONE,
        VARMAP_ID_GAME_OPTIONS,
        VARMAP_ID_POWERS,
        VARMAP_ID_ELAPSED_TIME_MS,
        VARMAP_ID_ACTUAL_ROOM,
        VARMAP_ID_LIFE_TOTAL,
        VARMAP_ID_LIFE_ACTUAL,
        VARMAP_ID_ITEMS_COLLECTED,
        VARMAP_ID_EVENTS_OCCURRED,
        VARMAP_ID_SELECTED_CHARMS,
        VARMAP_ID_OTHER_WORLD,
        VARMAP_ID_OTHER_WORLD_TRANSITION_ACTIVE,
        VARMAP_ID_OTHER_WORLD_TRANSITION_PROGRESS,
        VARMAP_ID_OTHER_WORLD_MODE,
        VARMAP_ID_GAMESTATUS,
        VARMAP_ID_PRESSED_KEYS,
        VARMAP_ID_MOUSE_PROPERTIES,
        VARMAP_ID_PLAYER_POSITION,
        VARMAP_ID_TOTAL
        /* > ATG 1 END < */
    }

    
}
